// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckModpack() {
  return window['go']['main']['App']['CheckModpack']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function LoadOptions() {
  return window['go']['main']['App']['LoadOptions']();
}

export function SaveOptions(arg1, arg2) {
  return window['go']['main']['App']['SaveOptions'](arg1, arg2);
}

export function UpdateModpack(arg1) {
  return window['go']['main']['App']['UpdateModpack'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
