// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckModpack():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LaunchGame(arg1:string,arg2:number):Promise<void>;

export function LoadOptions():Promise<main.Options>;

export function SaveOptions(arg1:string,arg2:number):Promise<void>;

export function UpdateModpack(arg1:main.ModpackManifest):Promise<void>;

export function Version():Promise<string>;
